name: Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    # Name the Job
    name: Test 
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine and runs the tests with coverage and generates badges
      - name: Test
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run test:badges
        env:
            CI: true
